DELETE FROM providers WHERE id='com.meshnetprotocol.ai';

INSERT INTO providers (
  id,
  name,
  description,
  tags_json,
  author,
  updated_at,
  price_per_gb_usd,
  visibility,
  status,
  config_json,
  routing_rules_json
) VALUES (
  'com.meshnetprotocol.ai',
  '官方供应商 AI 专用',
  'AI 专用的分流配置：默认直连，仅对主流 AI、Google 及 X/Twitter 相关域名强制走代理，便于在受限网络环境下学习与使用最新 AI 产品，同时尽量不影响其它日常上网流量。',
  '["Official","AI","SplitTunnel","ForceProxy"]',
  'OpenMesh Team',
  '2026-02-10T00:00:00Z',
  0.0,
  'public',
  'active',
  '{"dns":{"final":"google-dns","reverse_mapping":true,"servers":[{"detour":"proxy","server":"dns.google","tag":"google-dns","type":"https"},{"detour":"direct","server":"223.5.5.5","tag":"local-dns","type":"udp"}],"rules":[{"rule_set":"geosite-geolocation-cn","server":"local-dns"}],"strategy":"prefer_ipv4"},"inbounds":[{"address":["172.18.0.1/30","fdfe:dcba:9876::1/126"],"auto_route":true,"route_exclude_address":["127.0.0.0/8","10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","169.254.0.0/16","223.5.5.5/32","::1/128","fc00::/7","fe80::/10"],"strict_route":false,"tag":"tun-in","type":"tun"}],"experimental":{"cache_file":{"enabled":true}},"log":{"level":"warn"},"outbounds":[{"type":"shadowsocks","tag":"meshflux150","server":"216.128.182.150","server_port":10086,"method":"aes-256-gcm","password":"yourpassword123"},{"type":"shadowsocks","tag":"meshflux224","server":"64.176.39.224","server_port":29809,"method":"aes-256-gcm","password":"mMxNObzBIYKEw1qV"},{"type":"selector","tag":"proxy","outbounds":["meshflux150","meshflux224"],"default":"meshflux150"},{"domain_strategy":"ipv4_only","fallback_delay":"300ms","tag":"direct","type":"direct"}],"route":{"auto_detect_interface":true,"default_domain_resolver":"google-dns","final":"direct","rules":[{"action":"sniff"},{"action":"hijack-dns","protocol":"dns"},{"rule_set":"geosite-geolocation-cn","outbound":"direct"},{"rule_set":"geoip-cn","outbound":"direct"},{"ip_is_private":true,"outbound":"direct"}],"rule_set":[{"type":"remote","tag":"geoip-cn","format":"binary","url":"https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs","download_detour":"proxy","update_interval":"1d"},{"type":"remote","tag":"geosite-geolocation-cn","format":"binary","url":"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs","download_detour":"proxy","update_interval":"1d"}]}}',
  '{
  "proxy": {
    "domain": [
      "openai.com.cdn.cloudflare.net",
      "openaicom.imgix.net",
      "openaiapi-site.azureedge.net",
      "openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net"
    ],
    "domain_suffix": [
      "openai.com",
      "chatgpt.com",
      "oaistatic.com",
      "oaiusercontent.com",
      "sora.com",
      "anthropic.com",
      "claude.ai",
      "perplexity.ai",
      "poe.com",
      "huggingface.co",
      "hf.co",
      "replicate.com",
      "openrouter.ai",
      "together.ai",
      "cohere.com",
      "mistral.ai",
      "groq.com",
      "stability.ai",
      "dreamstudio.ai",
      "midjourney.com",
      "runwayml.com",
      "luma.ai",
      "pika.art",
      "ideogram.ai",
      "leonardo.ai",
      "krea.ai",
      "elevenlabs.io",
      "suno.com",
      "heygen.com",
      "synthesia.io",
      "discord.com",
      "discordapp.com",
      "discord.gg",
      "discordcdn.com",
      "twitter.com",
      "x.com",
      "t.co",
      "twimg.com",
      "twttr.com",
      "tweetdeck.com",
      "google.com",
      "googleapis.com",
      "gstatic.com",
      "googleusercontent.com",
      "gmail.com",
      "youtube.com",
      "youtu.be",
      "ytimg.com",
      "googlevideo.com",
      "ggpht.com",
      "workers.dev"
    ]
  }
}'
);
