DELETE FROM providers WHERE id='com.meshnetprotocol.ai';

INSERT INTO providers (
  id,
  name,
  description,
  tags_json,
  author,
  updated_at,
  price_per_gb_usd,
  visibility,
  status,
  config_json,
  routing_rules_json
) VALUES (
  'com.meshnetprotocol.ai',
  '官方供应商 AI 专用',
  'AI 专用的分流配置：默认直连，仅对主流 AI、Google 及 X/Twitter 相关域名强制走代理，便于在受限网络环境下学习与使用最新 AI 产品，同时尽量不影响其它日常上网流量。',
  '["Official","AI","SplitTunnel","ForceProxy"]',
  'OpenMesh Team',
  '2026-03-04T21:20:00Z',
  0.0,
  'public',
  'active',
  '{"dns":{"servers":[{"tag":"local-dns","address":"223.5.5.5","detour":"direct"},{"tag":"google-dns","address":"https://dns.google/dns-query","detour":"primary-selector"}],"rules":[{"rule_set":"geosite-geolocation-cn","server":"local-dns"}],"final":"google-dns","strategy":"ipv4_only"},"inbounds":[{"type":"tun","tag":"tun-in","address":["198.18.0.1/15","fdfe:dcba::1/126"],"auto_route":true,"strict_route":false,"route_exclude_address":["127.0.0.0/8","10.0.0.0/8","172.16.0.0/12","192.168.0.0/16","169.254.0.0/16","223.5.5.5/32","::1/128","fc00::/7","fe80::/10"],"route_exclude_address_set":["geoip-cn"],"sniff":true,"sniff_override_destination":true}],"experimental":{"cache_file":{"enabled":true}},"log":{"level":"warn"},"outbounds":[{"type":"shadowsocks","tag":"meshflux150 [加拿大]","server":"216.128.182.150","server_port":14370,"method":"aes-256-gcm","password":"uqaflxM4EiDaCfDV"},{"type":"shadowsocks","tag":"meshflux17 [美国]","server":"45.77.4.17","server_port":11241,"method":"aes-256-gcm","password":"pFR8iKfvYmnEAzZ0"},{"type":"selector","tag":"primary-selector","outbounds":["meshflux150 [加拿大]","meshflux17 [美国]"],"default":"meshflux17 [美国]"},{"type":"direct","tag":"direct"}],"route":{"rules":[{"action":"sniff"},{"protocol":"dns","action":"hijack-dns"},{"domain_suffix":["google.com","googleapis.com","gstatic.com","googleusercontent.com","gvt1.com","gvt2.com","1e100.net","youtube.com","ytimg.com","ggpht.com","android.com","app-measurement.com","github.com","githubusercontent.com","twitter.com","telegram.org","claude.ai","openai.com","facebook.com","fbcdn.net","instagram.com","whatsapp.com","whatsapp.net","tiktok.com","byteoversea.com","netflix.com","bing.com","perplexity.ai","deepl.com"],"outbound":"primary-selector"},{"rule_set":"geosite-geolocation-cn","outbound":"direct"},{"rule_set":"geoip-cn","outbound":"direct"},{"domain_suffix":["localhost","local"],"outbound":"direct"},{"ip_is_private":true,"outbound":"direct"}],"final":"primary-selector","auto_detect_interface":true,"rule_set":[{"type":"remote","tag":"geoip-cn","format":"binary","url":"https://raw.githubusercontent.com/SagerNet/sing-geoip/rule-set/geoip-cn.srs","download_detour":"primary-selector","update_interval":"1d"},{"type":"remote","tag":"geosite-geolocation-cn","format":"binary","url":"https://raw.githubusercontent.com/SagerNet/sing-geosite/rule-set/geosite-geolocation-cn.srs","download_detour":"primary-selector","update_interval":"1d"}]}}',
  '{
  "proxy": {
    "domain": [
      "openai.com.cdn.cloudflare.net",
      "openaicom.imgix.net",
      "openaiapi-site.azureedge.net",
      "openaicom-api-bdcpf8c6d2e9atf6.z01.azurefd.net"
    ],
    "domain_suffix": [
      "openai.com",
      "chatgpt.com",
      "oaistatic.com",
      "oaiusercontent.com",
      "sora.com",
      "anthropic.com",
      "claude.ai",
      "perplexity.ai",
      "poe.com",
      "huggingface.co",
      "hf.co",
      "replicate.com",
      "openrouter.ai",
      "together.ai",
      "cohere.com",
      "mistral.ai",
      "groq.com",
      "stability.ai",
      "dreamstudio.ai",
      "midjourney.com",
      "runwayml.com",
      "luma.ai",
      "pika.art",
      "ideogram.ai",
      "leonardo.ai",
      "krea.ai",
      "elevenlabs.io",
      "suno.com",
      "heygen.com",
      "synthesia.io",
      "discord.com",
      "discordapp.com",
      "discord.gg",
      "discordcdn.com",
      "twitter.com",
      "x.com",
      "t.co",
      "twimg.com",
      "twttr.com",
      "tweetdeck.com",
      "google.com",
      "googleapis.com",
      "gstatic.com",
      "googleusercontent.com",
      "gmail.com",
      "youtube.com",
      "youtu.be",
      "ytimg.com",
      "googlevideo.com",
      "ggpht.com",
      "workers.dev"
    ]
  }
}'
);
