param(
    [string]$Configuration = "Release",
    [string]$ServiceName = "OpenMeshWinServiceP6",
    [switch]$SkipStopConflictingProcesses
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass -Force

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$scmScript = Join-Path $scriptRoot "Run-P6-Service-SCM.ps1"
$reportsDir = Join-Path $scriptRoot "reports"
$repoRoot = (Resolve-Path (Join-Path $scriptRoot "..\..")).Path

function Test-IsAdministrator {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Get-LatestScmReportPath {
    if (-not (Test-Path $reportsDir)) {
        return $null
    }
    $item = Get-ChildItem -Path $reportsDir -Filter "p6-service-scm-*.txt" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if ($null -eq $item) {
        return $null
    }
    return $item.FullName
}

$args = @(
    "-NoProfile",
    "-ExecutionPolicy", "Bypass",
    "-File", $scmScript,
    "-Configuration", $Configuration,
    "-ServiceName", $ServiceName,
    "-RequireAdmin"
)
if ($SkipStopConflictingProcesses) {
    $args += "-SkipStopConflictingProcesses"
}

$beforeReport = Get-LatestScmReportPath
$exitCode = 0

if (Test-IsAdministrator) {
    & powershell @args
    $exitCode = $LASTEXITCODE
} else {
    Write-Host "Current shell is not elevated. Relaunching with UAC elevation..."
    try {
        $proc = Start-Process -FilePath "powershell.exe" -ArgumentList $args -WorkingDirectory $repoRoot -Verb RunAs -Wait -PassThru
        $exitCode = [int]$proc.ExitCode
    }
    catch {
        throw "UAC elevation was cancelled or failed: $($_.Exception.Message)"
    }
}

if ($exitCode -ne 0) {
    $afterReport = Get-LatestScmReportPath
    if ($null -ne $afterReport -and $afterReport -ne $beforeReport) {
        Write-Host ("Latest SCM report: " + $afterReport)
        Get-Content -Path $afterReport | ForEach-Object { Write-Host $_ }
    } else {
        Write-Host "No new SCM report was generated by the elevated process."
        Write-Host "This usually means UAC was cancelled or elevated process could not access the repo path."
        Write-Host "Manual fallback:"
        Write-Host "1) Start an Administrator PowerShell."
        Write-Host ("2) Run: powershell -ExecutionPolicy Bypass -File `"" + $scmScript + "`" -Configuration `"" + $Configuration + "`" -ServiceName `"" + $ServiceName + "`" -RequireAdmin")
    }
    throw "Run-P6-Service-SCM.ps1 strict mode failed with exit code $exitCode."
}
