listen: :8444

tls:
  cert: ../server.crt
  key: ../server.key

auth:
  type: password
  password: test_password_node2

masquerade:
  type: proxy
  proxy:
    url: https://www.bing.com
    rewriteHost: true

bandwidth:
  up: 100 mbps
  down: 100 mbps

trafficStats:
  listen: 127.0.0.1:9444
  secret: stats_secret_node2

log:
  level: info
  file: ./logs/hysteria2.log
